use_frameworks!

platform :ios, '8.0'

target 'AutoRotation_Example' do
  pod 'AutoRotation', :path => '../'

  target 'AutoRotation_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
